### ISSUE TITLE
consider submitting to Ansible

### ISSUE THREAD

**Issue by aioue** [timraasveld/ansible-string-split-filter#2]
Would you consider submitting this to Ansible's filter modules? It's too darn useful :+1:

**Comment by timraasveld** [comment]
I'll give it a shot - submitting code to open source projects is a bit scary to me but there's only one way to learn :)

**Comment by jgrowl** [comment]
+1

**Comment by aioue** [comment]
They're adding in a lot more content for v2.

Submit in to this directory in the project - now's the time!

https://github.com/ansible/ansible/tree/devel/lib/ansible/plugins/filter

**Comment by sysreq0** [comment]
+1

**Comment by timraasveld** [comment]
According to the Ansible team it [is already in core](http://comments.gmane.org/gmane.comp.sysutils.ansible.devel/2023), but I haven't tested their suggestion yet because I haven't worked with Ansible for a while. Would anyone mind giving it a shot with the current Ansible version?

**Comment by alkuzad** [comment]
```yaml
---
- hosts: localhost
  tasks:
    - debug:
        msg: "Item: {{item}}"
      with_items: "{{ '1,2,3,4,5'.split(',') }}"
```

Output from ansible 2.1:
```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => (item=1) => {
    "item": "1",
    "msg": "Item: 1"
}
ok: [localhost] => (item=2) => {
    "item": "2",
    "msg": "Item: 2"
}
ok: [localhost] => (item=3) => {
    "item": "3",
    "msg": "Item: 3"
}
ok: [localhost] => (item=4) => {
    "item": "4",
    "msg": "Item: 4"
}
ok: [localhost] => (item=5) => {
    "item": "5",
    "msg": "Item: 5"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

But I do not know if it's ansible feature (hack?) only or general jinja. Both of them are poor documented.

**Comment by timraasveld** [comment]
@alkuzad, nice, thanks for reporting this. I'll add a link to your post on top of the README to avoid people installing the plugin unneccesarily 👍

**Comment by nkakouros** [comment]
This filter is still needed as what ansible offers is a method on strings, not a filter.

**Comment by timraasveld** [comment]
> This filter is still needed as what ansible offers is a method on strings, not a filter.

Can you give an example of a situation where a filter is better than a string method? I'm not that much into Ansible these days so your feedback is appreciated :-)

**Comment by nkakouros** [comment]
@timraasveld I had a string variable that I needed first to pass through some other filters, like this:

`string_var | trim | regex_replace('[\\s]+', ' ') | split(' ')`

I don't know how to use the split method in this example without creating first a new variable.

**Comment by aioue** [comment]
an unstested shot in the dark, try:

`string_var | trim | regex_replace('[\\s]+', ' ').split(' ')`
or
`string_var | trim | (regex_replace('[\\s]+', ' ')).split(' ')`

**Comment by nkakouros** [comment]
The first fails with:
`"msg": "template error while templating string: expected token 'end of print statement', got '.'. String: {{ 'asdasds' | trim | regex_replace('[\\\\s]+', ' ').split(' ') }}"`

and the second with:
`"msg": "template error while templating string: expected token 'name', got '('. String: {{ 'asdasds' | trim | (regex_replace('[\\\\s]+', ' ')).split(' ') }}"
`

**Comment by nkakouros** [comment]
I had to revisit this recently. In a similar case, I was able to use the following to avoid using this filter:
`variable_name: "{{ (lookup('file', 'file.txt')).split('\n') }}"`
So, the trick seems to be to wrap everything in parentheses before calling the method.

**Comment by nkakouros** [comment]
But then. having a filter allows one to use `map`. Consider a list like this:
```yaml
list_var:
- aaa bbb
- ccc ddd
- eee fff
```
The following:
```yaml
tuple_list: "{{ list_var | map('split', ' ') | list }}
```
will produce the wonderful:
```yaml
tuple_list:
- [aaa, bbb]
- [ccc, ddd]
- [eee, fff]
```

I don't think this is possible with the split method.
This will return a

**Comment by alkuzad** [comment]
@tterranigma one year later I will tell you one thing - if you consider filters for other things that default that you are overdesigning :D

**Comment by jpmontez** [comment]
Yeah, it's ridiculous that there isn't a split filter. Running into the same problem as @tterranigma on Ansible 2.6.

**Comment by aioue** [comment]
Since this filter adds value over the normal split didn't get PR'd into core, suggest actually submitting it.

**Comment by nkakouros** [comment]
I create [an issue on jinja2](https://github.com/pallets/jinja/issues/898) to have this merged. This will also make it available in ansible.

If it doesn't get accepted there, I will open a PR on ansible.
