### ISSUE TITLE
Working as expected inside templates!

### ISSUE THREAD

**Issue by MerryDan** [timraasveld/ansible-string-split-filter#6]
Tried the following:
{% for port in split(',',comma_delimited_string)) %}
{% for port in split(comma_delimited_string,',')) %}
{% for port in comma_delimited_string.split(',') %}
  {{ port }}
{% endfor %}

All end up just breaking the string up per letter not with the delimiter.

When using split in the template you use it the same as the README example with a pipe.
{% for port in comma_delimited_string|split(',') %}

**Comment by timraasveld** [comment]
Glad it works now for you 👍
