### ISSUE TITLE
Thank you (and a teeny issue)

### ISSUE THREAD

**Issue by alform** [timraasveld/ansible-string-split-filter#9]
This is a neat filter - as already remarked, it should be in core ansible.
Extremely minor:
"seperetor" in the code should be spelled separator instead.

**Comment by timraasveld** [comment]
Thanks, fixed.

According to the Ansible team it [is already in core](http://comments.gmane.org/gmane.comp.sysutils.ansible.devel/2023), but I haven't tested their suggestion yet.
